# Generated by Django 5.2 on 2025-04-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, related_name='vehicles', to='garagem.acessory'),
        ),
    ]
