# Generated by Django 5.2 on 2025-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0002_alter_vehicle_accessories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='accessories',
            field=models.ManyToManyField(related_name='vehicles', to='garagem.acessory'),
        ),
    ]
