# Generated by Django 5.2 on 2025-04-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0003_alter_vehicle_accessories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='description',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='customers', to='garagem.vehicle'),
        ),
    ]
